name: "Build docker"

on: [pull_request, push]

permissions: read-all

jobs:
  build_docker:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # v2.4.0

    - name: setup-go
      uses: actions/setup-go@fcdc43634adb5f7ae75a9d7a9b9361790f7293e2 # v2.1.5
      with:
        go-version: '1.17.1'

    - name: Enable docker experimental
      run: |
        echo $'{"experimental": true}' | sudo dd status=none of=/etc/docker/daemon.json
        sudo service docker restart
        docker version -f '{{.Server.Experimental}}'

    - name: build_docker
      run: NOPUSH=true ./build_docker.sh
      working-directory: build
