name: "Test"

on:
  pull_request:

permissions: read-all

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # v2.4.0
    - uses: actions/setup-go@fcdc43634adb5f7ae75a9d7a9b9361790f7293e2 # v2.1.5
      with:
        go-version: 1.17.1
    - name: Install libpcap-dev
      run: sudo apt-get install -y libpcap-dev
    - name: Run tests
      run: go test -v ./...
